language: c

sudo: false

cache:
  directories:
  - $HOME/.racket/download-cache

env:
- PATH=~/racket/bin:$PATH

before_install:
- export PKG=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
- echo $PKG
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- raco pkg config --set catalogs `cat catalog-config.txt`
- raco pkg install --auto $PKG-test
- raco pkg install --auto $PKG-typed
- raco pkg install --auto compiler-lib
- ls $HOME/.racket/download-cache

script:
- raco test --drdr -p $PKG-test
- raco test --drdr -p $PKG-typed

after_script:
