language: c

sudo: false

cache:
  directories:
  - $HOME/.racket/download-cache

env:
- PATH=~/racket/bin:$PATH
- PATH=~/racket/bin:$PATH  VARIANT=cs


before_install:
- export PKG=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
- echo $PKG
- |
    if [ "$VARIANT" = "cs" ]; then
      curl --location --fail --output installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-linux-cs-xenial.sh;
    else
      curl --location --fail --output installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh;
    fi
- sh installer.sh --in-place --dest ~/racket/

install:
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- raco pkg config --set catalogs `cat catalog-config.txt`
- raco pkg install --installation --auto $PKG-test
- raco pkg install --installation --auto $PKG-typed
- raco pkg install --installation --auto compiler-lib
- ls $HOME/.racket/download-cache
- racket -v

script:
- raco test --drdr -p $PKG-test
- raco test --drdr -p $PKG-typed

after_script:
