name: Build and Test

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-18.04
    container: racket/racket-ci:latest

    strategy:
      fail-fast: false
      matrix:
        vm: ['regular', 'CS']

    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'minimal'
        variant: ${{ matrix.vm }}
        version: 'current'
    - name: Install and setup
      run: |
        racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
        echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
        raco pkg config catalogs >> catalog-config.txt
        raco pkg config --set catalogs `cat catalog-config.txt`
        raco pkg install --installation --auto rackunit-test
        raco pkg install --installation --auto rackunit-typed
        raco pkg install --installation --auto compiler-lib
    - name: Run tests
      run: |
        raco test --drdr -p rackunit-test
        raco test --drdr -p rackunit-typed
